ten-pin-bowling/config/routes.rb
Rails.application.routes.draw do

  root 'games#index'

  resources :games do 
    member do
      post :add_player
      post :start
    end
  end

end

ten-pin-bowling/app/models/bowl.rb
class Bowl < ActiveRecord::Base

	belongs_to :frame
	
end

ten-pin-bowling/app/models/frame.rb
class Frame < ActiveRecord::Base

	belongs_to :game
	belongs_to :player

	has_many :bowls
end

ten-pin-bowling/app/models/game.rb
class Game < ActiveRecord::Base

	has_many :players, dependent: :destroy
	has_many :frames, dependent: :destroy

	validates :team, presence: true

	def team_name
		"Team #{team}"
	end

	def start
		self.started = true
		self.save
	end
	
end

ten-pin-bowling/app/models/player.rb
class Player < ActiveRecord::Base

	has_many :frames, dependent: :destroy

	belongs_to :game

	validates :name, presence: true

	def score
		"-"
	end
	
end

ten-pin-bowling/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ten-pin-bowling/app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :get_game, only: [:show, :destroy, :add_player, :start]

	def index
		@games = Game.all
	end

	def show
		# @game = Game.find_by(params[:id])
	end

	def new
		@game = Game.new
	end

	def create
		@game = Game.new(game_params)

		if @game.save
			redirect_to @game
		else
			redirect_to games_path, alert: 'Invalid Team Name'
		end
	end

	def add_player
		@game.players.new(name: params[:player][:name])

		flash = "Invalid name" unless @game.save

		redirect_to @game, alert: flash
	end

	def start
		if@game.players.size > 0
			@game.start
			flash = "Game Started"
		else
			flash = "Game requires at least 1 player"
		end

		redirect_to @game, alert: flash
	end

	def destroy
		@game.destroy
		redirect_to games_path
	end

	private

	def game_params
		params.require(:game).permit(:team)
	end

	def get_game
		@game = Game.find(params[:id])
	end

end

ten-pin-bowling/app/helpers/application_helper.rb
module ApplicationHelper
end

ten-pin-bowling/app/helpers/games_helper.rb
module GamesHelper
end

ten-pin-bowling/app/views/games/_add_player_form.html.erb
<%= form_for :player, url: add_player_game_path do |form| %>

	<%= form.text_field :name, placeholder: "Player Name" %>

	<%= form.button "Add Player" %>

<% end %>

ten-pin-bowling/app/views/games/_game.html.erb
<div class="game-link" id="<%= game.id %>">
	<%= link_to "Team #{game.team}", game %>
	<%= link_to 'Delete Game', game_path(game), method: 'delete' %>
</div>

ten-pin-bowling/app/views/games/_links.html.erb
<div class="links">
	<%= link_to 'New Game', new_game_path %>
	<%= link_to 'Games List', games_path %>
</div>

ten-pin-bowling/app/views/games/_player.html.erb
<div class="player">
	<%= player.name %>
</div>

ten-pin-bowling/app/views/games/index.html.erb
<h1>Games Index</h1>
<% provide(:title, "Games List") %>

<%= render partial: 'game', collection: @games %>

ten-pin-bowling/app/views/games/new.html.erb
<% provide(:title, "New Game") %>

<%= form_for @game, url: games_path do |form| %>

	<%= form.text_field :team, placeholder: "Team Name" %>

	<%= form.button "Create Game" %>

<% end %>

ten-pin-bowling/app/views/games/show.html.erb
<% provide(:title, "Team #{@game.team}") %>

<h2>
	Players
</h2>

<% unless @game.started %>
	<%= render partial: 'add_player_form' %>

	<%= form_for :start_game, url: start_game_path do |form| %>
		<%=form.button 'Start Game' %>
	<% end %>

<% end %>

<%= render partial: 'player', collection: @game.players %>

ten-pin-bowling/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TenPinBowling</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/links' %>

	<div class ="title">
		<h1><%= yield(:title) %></h1>
	</div>

	<% flash.each do |key, value| %>
		<%= content_tag :div, value, class: "flash #{key}" %>
	<% end %>
<%= yield %>

</body>
</html>